/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveRouteImport } from './routes/live'
import { Route as CouncilSlugRouteImport } from './routes/council.$slug'
import { Route as SyllabusSlugRouteImport } from './routes/syllabus.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncilSlugRoute = CouncilSlugRouteImport.update({
  id: '/council/$slug',
  path: '/council/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusSlugRoute = SyllabusSlugRouteImport.update({
  id: '/syllabus/$slug',
  path: '/syllabus/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/council/$slug': typeof CouncilSlugRoute
  '/syllabus/$slug': typeof SyllabusSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/council/$slug': typeof CouncilSlugRoute
  '/syllabus/$slug': typeof SyllabusSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/council/$slug': typeof CouncilSlugRoute
  '/syllabus/$slug': typeof SyllabusSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/live' | '/council/$slug' | '/syllabus/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/live' | '/council/$slug' | '/syllabus/$slug'
  id: '__root__' | '/' | '/live' | '/council/$slug' | '/syllabus/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveRoute: typeof LiveRoute
  CouncilSlugRoute: typeof CouncilSlugRoute
  SyllabusSlugRoute: typeof SyllabusSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/council/$slug': {
      id: '/council/$slug'
      path: '/council/$slug'
      fullPath: '/council/$slug'
      preLoaderRoute: typeof CouncilSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus/$slug': {
      id: '/syllabus/$slug'
      path: '/syllabus/$slug'
      fullPath: '/syllabus/$slug'
      preLoaderRoute: typeof SyllabusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveRoute: LiveRoute,
  CouncilSlugRoute: CouncilSlugRoute,
  SyllabusSlugRoute: SyllabusSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
